name: Build & Publish Docker image
on:
  release:
    types: [ created ]
    secrets:
      DOCKER_USERNAME:
        required: true
        description: DockerHub Username
      DOCKER_TOKEN:
        required: true
        description: DockerHub Access Token
      GITEA_REGISTRY:
        required: true
        description: Gitea Container Registry URL
      GITEA_USERNAME:
        required: true
        description: Gitea Username
      GITEA_TOKEN:
        required: true
        description: Gitea Access Token
    workflow_dispatch:
      inputs:
        version:
          type: string
          description: Version number
          required: true
jobs:
  publish:
    name: Build & Publish to DockerHub, GitHub Packages and Gitea
    runs-on: ubuntu-20.04  # Node issues with arm v7 with latest: https://github.com/parse-community/parse-server/pull/8905
    if: contains(github.event.head_commit.message, '[no build]') == false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Establish variables
        id: vars
        run: |
          echo "version=${{ github.event.inputs.version || github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
          echo "today=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
          echo "year=$(date +'%Y')" >> "$GITHUB_OUTPUT"
          echo "container_name=python-3.x-node-18.19.0-alpine3.19" >> "$GITHUB_OUTPUT"

      - name: Display variables
        run: |
          echo "Version: ${{ steps.vars.outputs.version }}"
          echo "Today: ${{ steps.vars.outputs.today }}"
          echo "Year: ${{ steps.vars.outputs.year }}"
          echo "Container Name: ${{ steps.vars.outputs.container_name }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: docker-buildx

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.GITEA_REGISTRY }}
          username: ${{ secrets.GITEA_USERNAME }}
          password: ${{ secrets.GITEA_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.docker-buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/armhf,linux/arm64
          tags: |
            nwithan8/${{ steps.vars.outputs.container_name }}:latest
            nwithan8/${{ steps.vars.outputs.container_name }}:${{ steps.vars.outputs.version }}
            ghcr.io/nwithan8/${{ steps.vars.outputs.container_name }}:latest
            ghcr.io/nwithan8/${{ steps.vars.outputs.container_name }}:${{ steps.vars.outputs.version }}
            ${{ secrets.GITEA_REGISTRY }}/nwithan8/${{ steps.vars.outputs.container_name }}:latest
            ${{ secrets.GITEA_REGISTRY }}/nwithan8/${{ steps.vars.outputs.container_name }}:${{ steps.vars.outputs.version }}
          labels: |
            org.opencontainers.image.title=${{ steps.vars.outputs.container_name }}
            org.opencontainers.image.version=${{ steps.vars.outputs.version }}
            org.opencontainers.image.created=${{ steps.vars.outputs.today }}
